hydra:
  output_subdir: null
  run:
    dir: .

datafiles:
  global_temperature: 'global_temperature.txt'
  ocean_warming: 'ocean_heat.csv'
  co2_emissions: 'owid-co2-data.csv'
  renewable_energy_share: 'renewable_share_energy.csv'
  world_employment_rate: 'World_Employment_Rate.csv'
  world_population: 'world_population.csv'
  oil_consumption_per_capita: 'oil_consumption_per_capita.csv'
  global_energy_substitution: 'global_energy_substitution.csv'
  world_gdp: 'world_gdp.csv'

timeframes:
  year_initial : 1965
  year_end : 2019

univariate_lstm_model:
  scaler: 'MinMaxScaler'
  test_size_split: 0.1
  nr_lstm_layers: 2
  nr_dense_layers: 1
  units_per_layer:
    LSTM_1: 200
    LSTM_2: 180
    DENSE_1: 80
  dense_layer_activation: 'relu'
  loss: 'mean_squared_error'
  optimizer: 'Adam'
  metrics:
    - 'MeanSquaredError'
    - 'MeanAbsoluteError'
  epochs: 110

best_model: 'models/univar_lstm_model/model_4'