hydra:
  output_subdir: null
  run:
    dir: .

datafiles:
  global_temperature: 'global_temperature.txt'
  ocean_warming: 'ocean_heat.csv'
  co2_emissions: 'owid-co2-data.csv'
  renewable_energy_share: 'renewable_share_energy.csv'
  world_employment_rate: 'World_Employment_Rate.csv'
  world_population: 'world_population.csv'
  oil_consumption_per_capita: 'oil_consumption_per_capita.csv'
  global_energy_substitution: 'global_energy_substitution.csv'
  world_gdp: 'world_gdp.csv'

best_model: 'models/univar_lstm_model/model_3'